Apower <- read.table("household_power_consumption.txt", header=TRUE, sep=";",stringsAsFactors=FALSE, na.strings = c("?", ""))
Bpower <- subset(Apower, Apower$Date %in% c("1/2/2007", "2/2/2007"))
Bpower$Date <- as.Date(Bpower$Date, format="%d/%m/%Y")
Bpower$date <- paste(Bpower$Date, Bpower$Time)
Bpower$date_time <- strptime(Bpower$date, "%Y-%m-%d %H:%M:%S") 

png(file = "plot3.png")
plot3 <- with(Bpower, plot(date_time, Sub_metering_1, type="l",ylab="Energy sub metering", xlab= ""))
with(subset(Bpower),points(date_time, Sub_metering_2, type="l", col="red"))
with(subset(Bpower),points(date_time, Sub_metering_3, type="l", col="blue"))
legend("topright", lty=1, col=c("black", "red", "blue"), legend=c("Sub_metering_1","Sub_metering_2", "Sub_metering_3"))
dev.off()